# Generated by Django 3.2.4 on 2021-06-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
